/**
 * Writes supabase/seed/demo-content.sql from scripts/demo/content.mjs.
 *
 *   node scripts/demo/build-seed.mjs
 *
 * The SQL is idempotent: it replaces every demo invitation (is_demo = true)
 * and refreshes the catalogue fields of every template. It never touches
 * customer invitations, package prices or contact settings.
 */
import { mkdir, writeFile } from "node:fs/promises";

import { DEMOS, GIFTS, IMAGE_SLOTS, STORIES, WISHES, imagePath } from "./content.mjs";

const q = (value) => (value == null ? "null" : `'${String(value).replace(/'/g, "''")}'`);
const arr = (values) => `array[${values.map(q).join(", ")}]::text[]`;

const FEATURES = {
  music: false,
  countdown: true,
  maps: true,
  story: true,
  gallery: true,
  dressCode: true,
  livestream: true,
  rsvp: true,
  wishes: true,
  gift: true,
  guestPersonalization: true,
};

const TIME_ZONES = { "cobalt-riviera": "Asia/Makassar" };

function demoSql(demo) {
  const slug = `demo-${demo.theme}`;
  const settings = {
    features: FEATURES,
    timeZone: TIME_ZONES[demo.theme] ?? "Asia/Jakarta",
    dressCode: demo.dressCode,
  };
  const gallery = IMAGE_SLOTS.filter((slot) => slot.aspectRatio);
  const mapsUrl = (address) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;

  return `-- ${demo.title} (${demo.theme})
do $$
declare
  inv_id uuid;
begin
  insert into public.invitations (
    type, title, slug, theme_id, status, event_date, venue_summary, package_key, is_demo,
    published_at, expires_at, cover_image_path, opening_quote, opening_message, closing_message, settings
  )
  select ${q(demo.type)}, ${q(demo.title)}, ${q(slug)}, t.id, 'published', ${q(demo.eventDate)}, ${q(demo.venue)},
    ${q(demo.package_key)}, true, now(), null, ${q(imagePath(demo.theme, "cover.jpg"))},
    ${q(demo.opening_quote)}, ${q(demo.opening_message)}, ${q(demo.closing_message)}, ${q(JSON.stringify(settings))}::jsonb
  from public.themes t where t.slug = ${q(demo.theme)}
  returning id into inv_id;

  insert into public.invitation_people (invitation_id, role, full_name, nickname, father_name, mother_name, photo_path, bio, sort_order)
  values
${demo.people
  .map(
    (person, index) =>
      `    (inv_id, ${q(person.role)}, ${q(person.fullName)}, ${q(person.nickname)}, ${q(person.father)}, ${q(person.mother)}, ${q(imagePath(demo.theme, `person-${index + 1}.jpg`))}, ${q(person.bio)}, ${index})`,
  )
  .join(",\n")};

  insert into public.invitation_events (invitation_id, event_type, title, event_date, start_time, end_time, venue_name, address, maps_url, livestream_url, sort_order)
  values
${demo.events
  .map(
    (event, index) =>
      `    (inv_id, ${q(event.type)}, ${q(event.title)}, ${q(event.date)}, ${q(event.start)}, ${q(event.end)}, ${q(event.venue)}, ${q(event.address)}, ${q(mapsUrl(`${event.venue}, ${event.address}`))}, ${q(event.livestream ?? null)}, ${index})`,
  )
  .join(",\n")};

  insert into public.invitation_stories (invitation_id, title, year_label, description, image_path, sort_order)
  values
${STORIES.map(
  (story, index) =>
    `    (inv_id, ${q(story.title)}, ${q(story.year)}, ${q(story.description)}, ${q(imagePath(demo.theme, `story-${index + 1}.jpg`))}, ${index})`,
).join(",\n")};

  insert into public.gallery_items (invitation_id, image_path, alt_text, aspect_ratio, sort_order)
  values
${gallery
  .map(
    (slot, index) =>
      `    (inv_id, ${q(imagePath(demo.theme, slot.file))}, ${q(`Foto contoh ${index + 1}`)}, ${q(slot.aspectRatio)}, ${index})`,
  )
  .join(",\n")};

  insert into public.gift_accounts (invitation_id, provider_type, provider_name, account_number, account_name, sort_order)
  values
${GIFTS.map((gift, index) => `    (inv_id, ${q(gift.type)}, ${q(gift.provider)}, ${q(gift.number)}, ${q(gift.name)}, ${index})`).join(",\n")};

  insert into public.wishes (invitation_id, guest_name, message, is_visible, created_at)
  values
${WISHES.map((wish, index) => `    (inv_id, ${q(wish.name)}, ${q(wish.message)}, true, now() - interval '${(index + 1) * 5} hours')`).join(",\n")};
end $$;

update public.themes set
  tagline = ${q(demo.tagline)},
  description = ${q(demo.description)},
  event_types = ${arr(["wedding"])},
  screenshot_paths = ${arr([1, 2, 3].map((n) => imagePath(demo.theme, `screen-${n}.jpg`)))},
  sort_order = ${demo.sortOrder},
  is_listed = true
where slug = ${q(demo.theme)};
`;
}

const sql = `-- Demo content for the Temuraya marketing site.
-- Generated by scripts/demo/build-seed.mjs from scripts/demo/content.mjs; edit those, not this file.
-- Images are static files in public/demo/<theme>/ ("Sample N" placeholders).
-- Safe to re-run: replaces demo invitations only.

begin;

delete from public.invitations where is_demo;

${DEMOS.map(demoSql).join("\n")}
commit;
`;

const dir = new URL("../../supabase/seed/", import.meta.url);
await mkdir(dir, { recursive: true });
await writeFile(new URL("demo-content.sql", dir), sql);
console.log(`wrote supabase/seed/demo-content.sql (${DEMOS.length} demos)`);
