-- Demo content for the Temuraya marketing site.
-- Generated by scripts/demo/build-seed.mjs from scripts/demo/content.mjs; edit those, not this file.
-- Images are static files in public/demo/<theme>/ ("Sample N" placeholders).
-- Safe to re-run: replaces demo invitations only.

begin;

delete from public.invitations where is_demo;

-- Pernikahan Sekar & Damar (nusantara-ivory)
do $$
declare
  inv_id uuid;
begin
  insert into public.invitations (
    type, title, slug, theme_id, status, event_date, venue_summary, package_key, is_demo,
    published_at, expires_at, cover_image_path, opening_quote, opening_message, closing_message, settings
  )
  select 'wedding', 'Pernikahan Sekar & Damar', 'demo-nusantara-ivory', t.id, 'published', '2027-05-15', 'Pendopo Sample, Yogyakarta',
    'grand', true, now(), null, '/demo/nusantara-ivory/cover.jpg',
    'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan dari jenismu sendiri, supaya kamu merasa tenteram kepadanya. (QS. Ar-Rum: 21)', 'Dengan memohon rahmat Tuhan Yang Maha Esa, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada hari bahagia kami.', 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir. Terima kasih atas doa dan restunya.', '{"features":{"music":false,"countdown":true,"maps":true,"story":true,"gallery":true,"dressCode":true,"livestream":true,"rsvp":true,"wishes":true,"gift":true,"guestPersonalization":true},"timeZone":"Asia/Jakarta","dressCode":{"description":"Busana batik atau kebaya dengan nuansa hangat.","groups":[{"label":"Tamu","colors":["#A87A3D","#E9DCC4","#2F4A3A"]}]}}'::jsonb
  from public.themes t where t.slug = 'nusantara-ivory'
  returning id into inv_id;

  insert into public.invitation_people (invitation_id, role, full_name, nickname, father_name, mother_name, photo_path, bio, sort_order)
  values
    (inv_id, 'bride', 'Sekar Ayu Larasati', 'Sekar', 'Bapak Sample Wiryo', 'Ibu Sample Ratna', '/demo/nusantara-ivory/person-1.jpg', 'Putri pertama', 0),
    (inv_id, 'groom', 'Damar Prakoso', 'Damar', 'Bapak Sample Hadi', 'Ibu Sample Sri', '/demo/nusantara-ivory/person-2.jpg', 'Putra kedua', 1);

  insert into public.invitation_events (invitation_id, event_type, title, event_date, start_time, end_time, venue_name, address, maps_url, livestream_url, sort_order)
  values
    (inv_id, 'Sakral', 'Akad Nikah', '2027-05-15', '08:00', '10:00', 'Masjid Sample', 'Jl. Contoh No. 1, Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Masjid%20Sample%2C%20Jl.%20Contoh%20No.%201%2C%20Yogyakarta', null, 0),
    (inv_id, 'Perayaan', 'Resepsi', '2027-05-15', '11:00', '14:00', 'Pendopo Sample', 'Jl. Contoh No. 12, Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Pendopo%20Sample%2C%20Jl.%20Contoh%20No.%2012%2C%20Yogyakarta', 'https://www.youtube.com/', 1),
    (inv_id, 'Syukuran', 'Ngunduh Mantu', '2027-05-22', '10:00', '13:00', 'Rumah Keluarga Sample', 'Jl. Contoh No. 7, Magelang', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Keluarga%20Sample%2C%20Jl.%20Contoh%20No.%207%2C%20Magelang', null, 2);

  insert into public.invitation_stories (invitation_id, title, year_label, description, image_path, sort_order)
  values
    (inv_id, 'Pertama bertemu', '2019', 'Cerita contoh: kami bertemu di sebuah acara kampus dan mulai berbincang tanpa henti.', '/demo/nusantara-ivory/story-1.jpg', 0),
    (inv_id, 'Menjalin cerita', '2022', 'Cerita contoh: dari teman dekat menjadi pasangan yang saling menguatkan.', '/demo/nusantara-ivory/story-2.jpg', 1),
    (inv_id, 'Melangkah bersama', '2026', 'Cerita contoh: dengan restu keluarga, kami memutuskan untuk melangkah ke jenjang berikutnya.', '/demo/nusantara-ivory/story-3.jpg', 2);

  insert into public.gallery_items (invitation_id, image_path, alt_text, aspect_ratio, sort_order)
  values
    (inv_id, '/demo/nusantara-ivory/gallery-01.jpg', 'Foto contoh 1', 'portrait_3_4', 0),
    (inv_id, '/demo/nusantara-ivory/gallery-02.jpg', 'Foto contoh 2', 'landscape_4_3', 1),
    (inv_id, '/demo/nusantara-ivory/gallery-03.jpg', 'Foto contoh 3', 'square_1_1', 2),
    (inv_id, '/demo/nusantara-ivory/gallery-04.jpg', 'Foto contoh 4', 'portrait_4_5', 3),
    (inv_id, '/demo/nusantara-ivory/gallery-05.jpg', 'Foto contoh 5', 'landscape_16_9', 4),
    (inv_id, '/demo/nusantara-ivory/gallery-06.jpg', 'Foto contoh 6', 'portrait_3_4', 5),
    (inv_id, '/demo/nusantara-ivory/gallery-07.jpg', 'Foto contoh 7', 'square_1_1', 6),
    (inv_id, '/demo/nusantara-ivory/gallery-08.jpg', 'Foto contoh 8', 'landscape_4_3', 7),
    (inv_id, '/demo/nusantara-ivory/gallery-09.jpg', 'Foto contoh 9', 'portrait_4_5', 8),
    (inv_id, '/demo/nusantara-ivory/gallery-10.jpg', 'Foto contoh 10', 'portrait_3_4', 9),
    (inv_id, '/demo/nusantara-ivory/gallery-11.jpg', 'Foto contoh 11', 'landscape_16_9', 10),
    (inv_id, '/demo/nusantara-ivory/gallery-12.jpg', 'Foto contoh 12', 'square_1_1', 11);

  insert into public.gift_accounts (invitation_id, provider_type, provider_name, account_number, account_name, sort_order)
  values
    (inv_id, 'bank', 'Bank Sample', '1234567890', 'Nama Mempelai Sample', 0),
    (inv_id, 'ewallet', 'Dompet Digital Sample', '081200000000', 'Nama Mempelai Sample', 1);

  insert into public.wishes (invitation_id, guest_name, message, is_visible, created_at)
  values
    (inv_id, 'Tamu Sample 1', 'Selamat menempuh hidup baru! Semoga menjadi keluarga yang sakinah, mawaddah, warahmah.', true, now() - interval '5 hours'),
    (inv_id, 'Tamu Sample 2', 'Bahagia selalu untuk kalian berdua. Semoga langgeng sampai kakek nenek.', true, now() - interval '10 hours'),
    (inv_id, 'Tamu Sample 3', 'Turut berbahagia! Maaf belum bisa hadir, doa terbaik dari jauh.', true, now() - interval '15 hours'),
    (inv_id, 'Tamu Sample 4', 'Semoga cinta kalian terus tumbuh setiap hari. Selamat!', true, now() - interval '20 hours');
end $$;

update public.themes set
  tagline = 'Editorial Nusantara yang tenang, gading dan emas.',
  description = 'Nuansa gading dengan aksen emas dan detail Nusantara yang halus. Pembuka dengan melati yang berguguran, tipografi klasik, dan tata letak bergaya majalah.

Cocok untuk akad dan resepsi adat yang ingin tampil anggun dan bersahaja.',
  event_types = array['wedding']::text[],
  screenshot_paths = array['/demo/nusantara-ivory/screen-1.jpg', '/demo/nusantara-ivory/screen-2.jpg', '/demo/nusantara-ivory/screen-3.jpg']::text[],
  sort_order = 1,
  is_listed = true
where slug = 'nusantara-ivory';

-- Pernikahan Alya & Bima (terra-botanica)
do $$
declare
  inv_id uuid;
begin
  insert into public.invitations (
    type, title, slug, theme_id, status, event_date, venue_summary, package_key, is_demo,
    published_at, expires_at, cover_image_path, opening_quote, opening_message, closing_message, settings
  )
  select 'wedding', 'Pernikahan Alya & Bima', 'demo-terra-botanica', t.id, 'published', '2027-06-19', 'Kebun Sample, Bogor',
    'grand', true, now(), null, '/demo/terra-botanica/cover.jpg',
    'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan dari jenismu sendiri, supaya kamu merasa tenteram kepadanya. (QS. Ar-Rum: 21)', 'Dengan memohon rahmat Tuhan Yang Maha Esa, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada hari bahagia kami.', 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir. Terima kasih atas doa dan restunya.', '{"features":{"music":false,"countdown":true,"maps":true,"story":true,"gallery":true,"dressCode":true,"livestream":true,"rsvp":true,"wishes":true,"gift":true,"guestPersonalization":true},"timeZone":"Asia/Jakarta","dressCode":{"description":"Nuansa alam: hijau daun, terakota, dan krem.","groups":[{"label":"Tamu","colors":["#4E5B3A","#B5653E","#F2EBDD"]}]}}'::jsonb
  from public.themes t where t.slug = 'terra-botanica'
  returning id into inv_id;

  insert into public.invitation_people (invitation_id, role, full_name, nickname, father_name, mother_name, photo_path, bio, sort_order)
  values
    (inv_id, 'bride', 'Alya Kirana Putri', 'Alya', 'Bapak Sample Rahman', 'Ibu Sample Dewi', '/demo/terra-botanica/person-1.jpg', 'Putri kedua', 0),
    (inv_id, 'groom', 'Bima Aditya Nugraha', 'Bima', 'Bapak Sample Joko', 'Ibu Sample Lestari', '/demo/terra-botanica/person-2.jpg', 'Putra pertama', 1);

  insert into public.invitation_events (invitation_id, event_type, title, event_date, start_time, end_time, venue_name, address, maps_url, livestream_url, sort_order)
  values
    (inv_id, 'Sakral', 'Akad Nikah', '2027-06-19', '08:00', '10:00', 'Masjid Sample', 'Jl. Contoh No. 3, Bogor', 'https://www.google.com/maps/search/?api=1&query=Masjid%20Sample%2C%20Jl.%20Contoh%20No.%203%2C%20Bogor', null, 0),
    (inv_id, 'Perayaan', 'Resepsi', '2027-06-19', '11:00', '14:00', 'Kebun Sample', 'Jl. Contoh No. 21, Bogor', 'https://www.google.com/maps/search/?api=1&query=Kebun%20Sample%2C%20Jl.%20Contoh%20No.%2021%2C%20Bogor', 'https://www.youtube.com/', 1),
    (inv_id, 'Pesta kebun', 'Garden Party', '2027-06-20', '16:00', '19:00', 'Rumah Kaca Sample', 'Jl. Contoh No. 5, Bogor', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Kaca%20Sample%2C%20Jl.%20Contoh%20No.%205%2C%20Bogor', null, 2);

  insert into public.invitation_stories (invitation_id, title, year_label, description, image_path, sort_order)
  values
    (inv_id, 'Pertama bertemu', '2019', 'Cerita contoh: kami bertemu di sebuah acara kampus dan mulai berbincang tanpa henti.', '/demo/terra-botanica/story-1.jpg', 0),
    (inv_id, 'Menjalin cerita', '2022', 'Cerita contoh: dari teman dekat menjadi pasangan yang saling menguatkan.', '/demo/terra-botanica/story-2.jpg', 1),
    (inv_id, 'Melangkah bersama', '2026', 'Cerita contoh: dengan restu keluarga, kami memutuskan untuk melangkah ke jenjang berikutnya.', '/demo/terra-botanica/story-3.jpg', 2);

  insert into public.gallery_items (invitation_id, image_path, alt_text, aspect_ratio, sort_order)
  values
    (inv_id, '/demo/terra-botanica/gallery-01.jpg', 'Foto contoh 1', 'portrait_3_4', 0),
    (inv_id, '/demo/terra-botanica/gallery-02.jpg', 'Foto contoh 2', 'landscape_4_3', 1),
    (inv_id, '/demo/terra-botanica/gallery-03.jpg', 'Foto contoh 3', 'square_1_1', 2),
    (inv_id, '/demo/terra-botanica/gallery-04.jpg', 'Foto contoh 4', 'portrait_4_5', 3),
    (inv_id, '/demo/terra-botanica/gallery-05.jpg', 'Foto contoh 5', 'landscape_16_9', 4),
    (inv_id, '/demo/terra-botanica/gallery-06.jpg', 'Foto contoh 6', 'portrait_3_4', 5),
    (inv_id, '/demo/terra-botanica/gallery-07.jpg', 'Foto contoh 7', 'square_1_1', 6),
    (inv_id, '/demo/terra-botanica/gallery-08.jpg', 'Foto contoh 8', 'landscape_4_3', 7),
    (inv_id, '/demo/terra-botanica/gallery-09.jpg', 'Foto contoh 9', 'portrait_4_5', 8),
    (inv_id, '/demo/terra-botanica/gallery-10.jpg', 'Foto contoh 10', 'portrait_3_4', 9),
    (inv_id, '/demo/terra-botanica/gallery-11.jpg', 'Foto contoh 11', 'landscape_16_9', 10),
    (inv_id, '/demo/terra-botanica/gallery-12.jpg', 'Foto contoh 12', 'square_1_1', 11);

  insert into public.gift_accounts (invitation_id, provider_type, provider_name, account_number, account_name, sort_order)
  values
    (inv_id, 'bank', 'Bank Sample', '1234567890', 'Nama Mempelai Sample', 0),
    (inv_id, 'ewallet', 'Dompet Digital Sample', '081200000000', 'Nama Mempelai Sample', 1);

  insert into public.wishes (invitation_id, guest_name, message, is_visible, created_at)
  values
    (inv_id, 'Tamu Sample 1', 'Selamat menempuh hidup baru! Semoga menjadi keluarga yang sakinah, mawaddah, warahmah.', true, now() - interval '5 hours'),
    (inv_id, 'Tamu Sample 2', 'Bahagia selalu untuk kalian berdua. Semoga langgeng sampai kakek nenek.', true, now() - interval '10 hours'),
    (inv_id, 'Tamu Sample 3', 'Turut berbahagia! Maaf belum bisa hadir, doa terbaik dari jauh.', true, now() - interval '15 hours'),
    (inv_id, 'Tamu Sample 4', 'Semoga cinta kalian terus tumbuh setiap hari. Selamat!', true, now() - interval '20 hours');
end $$;

update public.themes set
  tagline = 'Herbarium cinta di antara daun dan bunga kering.',
  description = 'Seperti jurnal botani: tinta cokelat, sulur yang tumbuh saat digulir, dan benih yang mekar ketika undangan dibuka.

Cocok untuk pernikahan outdoor, garden party, dan konsep rustic.',
  event_types = array['wedding']::text[],
  screenshot_paths = array['/demo/terra-botanica/screen-1.jpg', '/demo/terra-botanica/screen-2.jpg', '/demo/terra-botanica/screen-3.jpg']::text[],
  sort_order = 2,
  is_listed = true
where slug = 'terra-botanica';

-- Pernikahan Nadia & Reza (midnight-atelier)
do $$
declare
  inv_id uuid;
begin
  insert into public.invitations (
    type, title, slug, theme_id, status, event_date, venue_summary, package_key, is_demo,
    published_at, expires_at, cover_image_path, opening_quote, opening_message, closing_message, settings
  )
  select 'wedding', 'Pernikahan Nadia & Reza', 'demo-midnight-atelier', t.id, 'published', '2027-08-21', 'Ballroom Sample, Jakarta',
    'grand', true, now(), null, '/demo/midnight-atelier/cover.jpg',
    'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan dari jenismu sendiri, supaya kamu merasa tenteram kepadanya. (QS. Ar-Rum: 21)', 'Dengan memohon rahmat Tuhan Yang Maha Esa, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada hari bahagia kami.', 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir. Terima kasih atas doa dan restunya.', '{"features":{"music":false,"countdown":true,"maps":true,"story":true,"gallery":true,"dressCode":true,"livestream":true,"rsvp":true,"wishes":true,"gift":true,"guestPersonalization":true},"timeZone":"Asia/Jakarta","dressCode":{"description":"Black tie. Gaun malam atau setelan gelap.","groups":[{"label":"Tamu","colors":["#14121A","#5E1A22","#D8C08A"]}]}}'::jsonb
  from public.themes t where t.slug = 'midnight-atelier'
  returning id into inv_id;

  insert into public.invitation_people (invitation_id, role, full_name, nickname, father_name, mother_name, photo_path, bio, sort_order)
  values
    (inv_id, 'bride', 'Nadia Salsabila', 'Nadia', 'Bapak Sample Arif', 'Ibu Sample Maya', '/demo/midnight-atelier/person-1.jpg', 'Putri ketiga', 0),
    (inv_id, 'groom', 'Reza Mahendra', 'Reza', 'Bapak Sample Teguh', 'Ibu Sample Indah', '/demo/midnight-atelier/person-2.jpg', 'Putra pertama', 1);

  insert into public.invitation_events (invitation_id, event_type, title, event_date, start_time, end_time, venue_name, address, maps_url, livestream_url, sort_order)
  values
    (inv_id, 'Sakral', 'Akad Nikah', '2027-08-21', '15:00', '16:30', 'Masjid Sample', 'Jl. Contoh No. 9, Jakarta', 'https://www.google.com/maps/search/?api=1&query=Masjid%20Sample%2C%20Jl.%20Contoh%20No.%209%2C%20Jakarta', null, 0),
    (inv_id, 'Perayaan', 'Resepsi Malam', '2027-08-21', '19:00', '22:00', 'Ballroom Sample', 'Jl. Contoh No. 88, Jakarta', 'https://www.google.com/maps/search/?api=1&query=Ballroom%20Sample%2C%20Jl.%20Contoh%20No.%2088%2C%20Jakarta', 'https://www.youtube.com/', 1),
    (inv_id, 'Pesta malam', 'After Party', '2027-08-21', '22:00', '23:30', 'Lounge Sample', 'Jl. Contoh No. 88, Jakarta', 'https://www.google.com/maps/search/?api=1&query=Lounge%20Sample%2C%20Jl.%20Contoh%20No.%2088%2C%20Jakarta', null, 2);

  insert into public.invitation_stories (invitation_id, title, year_label, description, image_path, sort_order)
  values
    (inv_id, 'Pertama bertemu', '2019', 'Cerita contoh: kami bertemu di sebuah acara kampus dan mulai berbincang tanpa henti.', '/demo/midnight-atelier/story-1.jpg', 0),
    (inv_id, 'Menjalin cerita', '2022', 'Cerita contoh: dari teman dekat menjadi pasangan yang saling menguatkan.', '/demo/midnight-atelier/story-2.jpg', 1),
    (inv_id, 'Melangkah bersama', '2026', 'Cerita contoh: dengan restu keluarga, kami memutuskan untuk melangkah ke jenjang berikutnya.', '/demo/midnight-atelier/story-3.jpg', 2);

  insert into public.gallery_items (invitation_id, image_path, alt_text, aspect_ratio, sort_order)
  values
    (inv_id, '/demo/midnight-atelier/gallery-01.jpg', 'Foto contoh 1', 'portrait_3_4', 0),
    (inv_id, '/demo/midnight-atelier/gallery-02.jpg', 'Foto contoh 2', 'landscape_4_3', 1),
    (inv_id, '/demo/midnight-atelier/gallery-03.jpg', 'Foto contoh 3', 'square_1_1', 2),
    (inv_id, '/demo/midnight-atelier/gallery-04.jpg', 'Foto contoh 4', 'portrait_4_5', 3),
    (inv_id, '/demo/midnight-atelier/gallery-05.jpg', 'Foto contoh 5', 'landscape_16_9', 4),
    (inv_id, '/demo/midnight-atelier/gallery-06.jpg', 'Foto contoh 6', 'portrait_3_4', 5),
    (inv_id, '/demo/midnight-atelier/gallery-07.jpg', 'Foto contoh 7', 'square_1_1', 6),
    (inv_id, '/demo/midnight-atelier/gallery-08.jpg', 'Foto contoh 8', 'landscape_4_3', 7),
    (inv_id, '/demo/midnight-atelier/gallery-09.jpg', 'Foto contoh 9', 'portrait_4_5', 8),
    (inv_id, '/demo/midnight-atelier/gallery-10.jpg', 'Foto contoh 10', 'portrait_3_4', 9),
    (inv_id, '/demo/midnight-atelier/gallery-11.jpg', 'Foto contoh 11', 'landscape_16_9', 10),
    (inv_id, '/demo/midnight-atelier/gallery-12.jpg', 'Foto contoh 12', 'square_1_1', 11);

  insert into public.gift_accounts (invitation_id, provider_type, provider_name, account_number, account_name, sort_order)
  values
    (inv_id, 'bank', 'Bank Sample', '1234567890', 'Nama Mempelai Sample', 0),
    (inv_id, 'ewallet', 'Dompet Digital Sample', '081200000000', 'Nama Mempelai Sample', 1);

  insert into public.wishes (invitation_id, guest_name, message, is_visible, created_at)
  values
    (inv_id, 'Tamu Sample 1', 'Selamat menempuh hidup baru! Semoga menjadi keluarga yang sakinah, mawaddah, warahmah.', true, now() - interval '5 hours'),
    (inv_id, 'Tamu Sample 2', 'Bahagia selalu untuk kalian berdua. Semoga langgeng sampai kakek nenek.', true, now() - interval '10 hours'),
    (inv_id, 'Tamu Sample 3', 'Turut berbahagia! Maaf belum bisa hadir, doa terbaik dari jauh.', true, now() - interval '15 hours'),
    (inv_id, 'Tamu Sample 4', 'Semoga cinta kalian terus tumbuh setiap hari. Selamat!', true, now() - interval '20 hours');
end $$;

update public.themes set
  tagline = 'Malam di ballroom, lampu sorot, dan kartu dansa.',
  description = 'Gelap dan berkelas: tinta malam, aksen sampanye, dan lampu sorot yang mengikuti pembacaan. Ada toast sampanye dan kartu dansa untuk tamu yang hadir.

Cocok untuk resepsi malam dan pesta formal.',
  event_types = array['wedding']::text[],
  screenshot_paths = array['/demo/midnight-atelier/screen-1.jpg', '/demo/midnight-atelier/screen-2.jpg', '/demo/midnight-atelier/screen-3.jpg']::text[],
  sort_order = 3,
  is_listed = true
where slug = 'midnight-atelier';

-- Pernikahan Mira & Raka (cobalt-riviera)
do $$
declare
  inv_id uuid;
begin
  insert into public.invitations (
    type, title, slug, theme_id, status, event_date, venue_summary, package_key, is_demo,
    published_at, expires_at, cover_image_path, opening_quote, opening_message, closing_message, settings
  )
  select 'wedding', 'Pernikahan Mira & Raka', 'demo-cobalt-riviera', t.id, 'published', '2027-09-18', 'Pantai Sample, Bali',
    'grand', true, now(), null, '/demo/cobalt-riviera/cover.jpg',
    'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan dari jenismu sendiri, supaya kamu merasa tenteram kepadanya. (QS. Ar-Rum: 21)', 'Dengan memohon rahmat Tuhan Yang Maha Esa, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada hari bahagia kami.', 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir. Terima kasih atas doa dan restunya.', '{"features":{"music":false,"countdown":true,"maps":true,"story":true,"gallery":true,"dressCode":true,"livestream":true,"rsvp":true,"wishes":true,"gift":true,"guestPersonalization":true},"timeZone":"Asia/Makassar","dressCode":{"description":"Linen dan warna laut: biru, putih, dan sentuhan jeruk.","groups":[{"label":"Tamu","colors":["#1D3E9E","#F7F4EC","#E8743B"]}]}}'::jsonb
  from public.themes t where t.slug = 'cobalt-riviera'
  returning id into inv_id;

  insert into public.invitation_people (invitation_id, role, full_name, nickname, father_name, mother_name, photo_path, bio, sort_order)
  values
    (inv_id, 'bride', 'Mira Anindya', 'Mira', 'Bapak Sample Made', 'Ibu Sample Ayu', '/demo/cobalt-riviera/person-1.jpg', 'Putri pertama', 0),
    (inv_id, 'groom', 'Raka Pratama', 'Raka', 'Bapak Sample Budi', 'Ibu Sample Rina', '/demo/cobalt-riviera/person-2.jpg', 'Putra kedua', 1);

  insert into public.invitation_events (invitation_id, event_type, title, event_date, start_time, end_time, venue_name, address, maps_url, livestream_url, sort_order)
  values
    (inv_id, 'Sakral', 'Pemberkatan', '2027-09-18', '10:00', '11:30', 'Kapel Sample', 'Jl. Contoh No. 2, Bali', 'https://www.google.com/maps/search/?api=1&query=Kapel%20Sample%2C%20Jl.%20Contoh%20No.%202%2C%20Bali', null, 0),
    (inv_id, 'Perayaan', 'Resepsi Senja', '2027-09-18', '16:00', '20:00', 'Pantai Sample', 'Jl. Contoh No. 45, Bali', 'https://www.google.com/maps/search/?api=1&query=Pantai%20Sample%2C%20Jl.%20Contoh%20No.%2045%2C%20Bali', 'https://www.youtube.com/', 1),
    (inv_id, 'Perpisahan', 'Farewell Brunch', '2027-09-19', '09:00', '11:00', 'Kafe Sample', 'Jl. Contoh No. 10, Bali', 'https://www.google.com/maps/search/?api=1&query=Kafe%20Sample%2C%20Jl.%20Contoh%20No.%2010%2C%20Bali', null, 2);

  insert into public.invitation_stories (invitation_id, title, year_label, description, image_path, sort_order)
  values
    (inv_id, 'Pertama bertemu', '2019', 'Cerita contoh: kami bertemu di sebuah acara kampus dan mulai berbincang tanpa henti.', '/demo/cobalt-riviera/story-1.jpg', 0),
    (inv_id, 'Menjalin cerita', '2022', 'Cerita contoh: dari teman dekat menjadi pasangan yang saling menguatkan.', '/demo/cobalt-riviera/story-2.jpg', 1),
    (inv_id, 'Melangkah bersama', '2026', 'Cerita contoh: dengan restu keluarga, kami memutuskan untuk melangkah ke jenjang berikutnya.', '/demo/cobalt-riviera/story-3.jpg', 2);

  insert into public.gallery_items (invitation_id, image_path, alt_text, aspect_ratio, sort_order)
  values
    (inv_id, '/demo/cobalt-riviera/gallery-01.jpg', 'Foto contoh 1', 'portrait_3_4', 0),
    (inv_id, '/demo/cobalt-riviera/gallery-02.jpg', 'Foto contoh 2', 'landscape_4_3', 1),
    (inv_id, '/demo/cobalt-riviera/gallery-03.jpg', 'Foto contoh 3', 'square_1_1', 2),
    (inv_id, '/demo/cobalt-riviera/gallery-04.jpg', 'Foto contoh 4', 'portrait_4_5', 3),
    (inv_id, '/demo/cobalt-riviera/gallery-05.jpg', 'Foto contoh 5', 'landscape_16_9', 4),
    (inv_id, '/demo/cobalt-riviera/gallery-06.jpg', 'Foto contoh 6', 'portrait_3_4', 5),
    (inv_id, '/demo/cobalt-riviera/gallery-07.jpg', 'Foto contoh 7', 'square_1_1', 6),
    (inv_id, '/demo/cobalt-riviera/gallery-08.jpg', 'Foto contoh 8', 'landscape_4_3', 7),
    (inv_id, '/demo/cobalt-riviera/gallery-09.jpg', 'Foto contoh 9', 'portrait_4_5', 8),
    (inv_id, '/demo/cobalt-riviera/gallery-10.jpg', 'Foto contoh 10', 'portrait_3_4', 9),
    (inv_id, '/demo/cobalt-riviera/gallery-11.jpg', 'Foto contoh 11', 'landscape_16_9', 10),
    (inv_id, '/demo/cobalt-riviera/gallery-12.jpg', 'Foto contoh 12', 'square_1_1', 11);

  insert into public.gift_accounts (invitation_id, provider_type, provider_name, account_number, account_name, sort_order)
  values
    (inv_id, 'bank', 'Bank Sample', '1234567890', 'Nama Mempelai Sample', 0),
    (inv_id, 'ewallet', 'Dompet Digital Sample', '081200000000', 'Nama Mempelai Sample', 1);

  insert into public.wishes (invitation_id, guest_name, message, is_visible, created_at)
  values
    (inv_id, 'Tamu Sample 1', 'Selamat menempuh hidup baru! Semoga menjadi keluarga yang sakinah, mawaddah, warahmah.', true, now() - interval '5 hours'),
    (inv_id, 'Tamu Sample 2', 'Bahagia selalu untuk kalian berdua. Semoga langgeng sampai kakek nenek.', true, now() - interval '10 hours'),
    (inv_id, 'Tamu Sample 3', 'Turut berbahagia! Maaf belum bisa hadir, doa terbaik dari jauh.', true, now() - interval '15 hours'),
    (inv_id, 'Tamu Sample 4', 'Semoga cinta kalian terus tumbuh setiap hari. Selamat!', true, now() - interval '20 hours');
end $$;

update public.themes set
  tagline = 'Surat cinta dari Mediterania.',
  description = 'Biru kobalt, porselen, dan matahari jeruk. Ombak yang surut saat dibuka, kartu pos untuk setiap konfirmasi, dan botol pesan untuk ucapan.

Cocok untuk destination wedding dan pernikahan di tepi pantai.',
  event_types = array['wedding']::text[],
  screenshot_paths = array['/demo/cobalt-riviera/screen-1.jpg', '/demo/cobalt-riviera/screen-2.jpg', '/demo/cobalt-riviera/screen-3.jpg']::text[],
  sort_order = 4,
  is_listed = true
where slug = 'cobalt-riviera';

commit;
